### ISSUE TITLE
Installing using Docker

### ISSUE THREAD

**Issue by leendersf** [StevenReitsma/bnd-quotes#1]
Hello,

Installing using Docker gives this error:
_Please type 'yes' or 'no': yes
Warning: Permanently added 'github.com,140.82.121.4' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository._

Can you please help me? It works fine using the public option.

**Comment by StevenReitsma** [comment]
I'm assuming you're trying to clone this project before you are building the Docker image? You will first have to create an SSH key to clone from GitHub (https://docs.github.com/en/authentication/connecting-to-github-with-ssh). Or you can clone using HTTP instead of SSH using `git clone https://github.com/StevenReitsma/bnd-quotes.git`.

**Comment by leendersf** [comment]
It works, except for the final step:

_docker run -it -p 80:80 bnd-quotes_

It says:

_Unable to find image 'bnd-quotes:latest' locally
docker: Error response from daemon: pull access denied for bnd-quotes, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'._

**Comment by StevenReitsma** [comment]
This is a pretty basic error. It means the image `bnd-quotes` is not present on your machine, which probably means you didn't execute the `docker build` step properly. Maybe there was an error while building or you forgot to include the `--tag bnd-quotes` flag. I just tested the snippet in the README and it still works fine, so please refer to the Docker docs for more information.
